### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#66]
Related to https://trello.com/c/61gLobK5/171-ui-improvements

- [x] https://github.com/liteflow-labs/starter-kit/issues/83
- [ ] https://github.com/liteflow-labs/starter-kit/issues/87
- [x] https://github.com/liteflow-labs/nft/issues/1965
- [x] https://github.com/liteflow-labs/starter-kit/issues/68
- [x] https://github.com/liteflow-labs/starter-kit/issues/70
- [x] https://github.com/liteflow-labs/starter-kit/issues/71
- [ ] https://github.com/liteflow-labs/starter-kit/issues/52
- [ ] https://github.com/liteflow-labs/starter-kit/issues/65
- [ ] https://github.com/liteflow-labs/starter-kit/issues/55
  - [ ] liteflow-labs/libraries#25
- [ ] https://github.com/liteflow-labs/starter-kit/issues/54
- [x] https://github.com/liteflow-labs/nft/issues/1730
- [ ] https://github.com/liteflow-labs/starter-kit/issues/56
- [x] https://github.com/liteflow-labs/starter-kit/issues/72
- [x] https://github.com/liteflow-labs/liteflow-js/issues/4
- [ ] https://github.com/liteflow-labs/starter-kit/issues/78
- [x] https://github.com/liteflow-labs/starter-kit/issues/84
- [x] https://github.com/liteflow-labs/libraries/issues/49
- [x] https://github.com/liteflow-labs/starter-kit/issues/79

**Comment by EmmanuelDrouin** [comment]
Closing this epic
