### ISSUE TITLE
General Template enhancement

### ISSUE THREAD

**Issue by NicolasMahe** [liteflow-labs/starter-kit#67]
Related to https://trello.com/c/FKFAEpXV/172-general-template-enhancement

- [x] https://github.com/liteflow-labs/starter-kit/issues/82
- [ ] https://github.com/liteflow-labs/starter-kit/issues/77
- [ ] https://github.com/liteflow-labs/starter-kit/issues/61
- [ ] https://github.com/liteflow-labs/starter-kit/issues/62
- [x] https://github.com/liteflow-labs/starter-kit/issues/74
- [ ] https://github.com/liteflow-labs/starter-kit/issues/75
- [ ] https://github.com/liteflow-labs/starter-kit/issues/76
- [ ] https://github.com/liteflow-labs/starter-kit/issues/85
- [ ] https://github.com/liteflow-labs/libraries/issues/51
- [ ] https://github.com/liteflow-labs/starter-kit/issues/86
- [x] https://github.com/liteflow-labs/starter-kit/issues/88
- [x] https://github.com/liteflow-labs/libraries/issues/55

**Comment by EmmanuelDrouin** [comment]
Closing this epic
